apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/bsutter-tenant/devfile-sample/devfile-sample@sha256:9819fbeece85b272a8ba81f20c15439d1ebb103f97cd022e10ae3911f3838e29
        name: my-nodejs
        resources: {}
status: {}
